name: Solar System Deploy Workflow


on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
#       - 'feature/*'



jobs:
  docker-build:
    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # - name: Docker Hub Login
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ${{ vars.CONTAINER_REGISTERY }}
    #     username: ${{ vars.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Build Docker Image for Testing
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system-mostafakassab:${{ github.sha }}

  

    - name: Docker Build
      run: docker build -t ${{ vars.CONTAINER_REGISTERY }}/${{ vars.DOCKERHUB_USERNAME }}/solar-system-mostafakassab:${{ github.sha }} .

    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login ${{ vars.CONTAINER_REGISTERY }} -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin

    - name: Docker Push
      run: docker push ${{ vars.CONTAINER_REGISTERY }}/${{ vars.DOCKERHUB_USERNAME }}/solar-system-mostafakassab:${{ github.sha }}


        
  dev-deploy:
    name: Deploy to Dev Env
    runs-on: ubuntu-latest
    needs: docker-build

    env:
      MONGO_URI: 'mongodb+srv://supercluster.d3jj.mongodb.net/superData'
      MONGO_USERNAME: ahmed
      KUBECONFIG: ./kubernetes/iticonfig.yaml
      NAMESPACE: mostafakassab
     
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install kubectl CLI
      uses: azure/setup-kubectl@v3
      with:
            version: 'latest'

    - name: Set up Kubeconfig
      run: kubectl get nodes
      env:
        KUBECONFIG: ./kubernetes/iticonfig.yaml

    - name: Fetch Kubernetes Cluster Details
      run: |
            kubectl version --client
            kubectl get namespaces
            echo "-----------------------------------------"
            kubectl get nodes
            echo "-----------------------------------------"
            kubectl get pods --all-namespaces -o wide


    - name: Replace tokens in manifests
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '_{_'
        tokenSuffix: '_}_'
        files: kubernetes/development/*.yaml
      env:
            NAMESPACE: mostafakassab
            REPLICAS: 2
            IMAGE: ${{ vars.CONTAINER_REGISTERY }}/${{ vars.DOCKERHUB_USERNAME }}/solar-system-mostafakassab:${{ github.sha }}


    - name: Show processed manifests
      run: cat kubernetes/development/*.yaml


    - name: Create MongoDB secret
      run: |
            kubectl get namespace ${{ env.NAMESPACE }} || \
            kubectl create namespace ${{ env.NAMESPACE }}
            kubectl -n ${{ env.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -
     
      env:
        KUBECONFIG: ./kubernetes/iticonfig.yaml



    - name: Deploy manifests
      run: kubectl apply -f kubernetes/development


    - name: Kubernetes Cluster Details After Deployment
      run: |
            sleep 30
            kubectl version --client
            kubectl get namespaces
            echo "-----------------------------------------"
            kubectl get nodes
            echo "-----------------------------------------"
            kubectl get pods --all-namespaces -o wide
            echo "-----------------------------------------"
            kubectl get services --all-namespaces
            echo "-----------------------------------------"
            kubectl get svc --namespace ${{ env.NAMESPACE }}
            echo "-----------------------------------------\n"-----------------------------------------""
            echo "Your Application is accessible at - http://$(kubectl get svc --namespace ${{ env.NAMESPACE }} | grep solar-system-kassab | awk '{ print $4 }'):3002"